# Generated by Django 4.0.3 on 2022-03-16 23:31

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airwaysinfoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
