# Generated by Django 4.0.3 on 2022-03-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airwaysinfoapp', '0002_alter_company_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
    ]
